import type { SpaceFloor } from './api'

export const FLOOR_LABELS: Record<SpaceFloor, { en: string; sq: string }> = {
  roof:      { en: 'Roof L+4',       sq: 'Çatia L+4' },
  l3:        { en: '3rd Floor',       sq: 'Kati 3' },
  l0:        { en: 'Ground Floor',    sq: 'Kati Përdhes' },
  l_minus_1: { en: 'B1 Floor',        sq: 'Kati B1' },
  exterior:  { en: 'Exterior Boxes',  sq: 'Kutitë Jashtë' },
}

export const FLOOR_ORDER: SpaceFloor[] = ['roof', 'l3', 'l0', 'l_minus_1', 'exterior']

export type Lang = 'en' | 'sq'

export const dict = {
  en: {
    book_now:        'book now',
    capacity:        'capacity',
    area:            'area',
    hourly_rate:     'hourly rate',
    available:       'available',
    reserved:        'reserved',
    blocked:         'blocked',
    pending:         'pending',
    floors:          'floors',
    spaces:          'spaces',
    select_floor:    'select floor',
    view_floor_plan: 'view floor plan',
    back:            'back',
    confirm:         'confirm',
    cancel:          'cancel',
    loading:         'loading...',
    error:           'something went wrong',
    attendees:       'attendees',
    start_time:      'start time',
    end_time:        'end time',
    setup_type:      'setup type',
    features:        'features',
    quote:           'quote',
    total:           'total',
    subtotal:        'subtotal',
    tax:             'tax',
    accept_quote:    'accept quote',
    tasks:           'tasks',
    dashboard:       'dashboard',
    events:          'events',
    inventory:       'inventory',
    conflicts:       'conflicts',
    ask_assistant:   'ask assistant',
  },
  sq: {
    book_now:        'rezervo tani',
    capacity:        'kapaciteti',
    area:            'sipërfaqja',
    hourly_rate:     'çmimi / orë',
    available:       'i lirë',
    reserved:        'i rezervuar',
    blocked:         'i bllokuar',
    pending:         'në pritje',
    floors:          'katet',
    spaces:          'hapësirat',
    select_floor:    'zgjidh katin',
    view_floor_plan: 'shiko planin',
    back:            'kthehu',
    confirm:         'konfirmo',
    cancel:          'anulo',
    loading:         'duke ngarkuar...',
    error:           'diçka shkoi keq',
    attendees:       'pjesëmarrës',
    start_time:      'fillimi',
    end_time:        'mbarimi',
    setup_type:      'lloji i ngritjes',
    features:        'veçoritë',
    quote:           'oferta',
    total:           'totali',
    subtotal:        'nëntotali',
    tax:             'tatimi',
    accept_quote:    'prano ofertën',
    tasks:           'detyrat',
    dashboard:       'paneli',
    events:          'ngjarjet',
    inventory:       'inventari',
    conflicts:       'konfliktet',
    ask_assistant:   'pyet asistentin',
  },
} as const

export type DictKey = keyof typeof dict.en
